# Generated by Django 5.1.7 on 2025-03-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingapp', '0003_admission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='students/')),
            ],
        ),
        migrations.DeleteModel(
            name='Admission',
        ),
    ]
